version: '3.5'

services:

  load:
    container_name: load
    hostname: load
    restart: always
    image: load

  mock-services:  
    container_name: mock-services
    hostname: mock-services
    restart: always
    image: mock-services
    expose:
      - 8080

  chat-services:
    container_name: chat-services
    hostname: chat-services
    restart: always
    image: nodejs-services
    expose:
      - 8001

  player-action-services:
    container_name: player-action-services
    hostname: player-action-services
    restart: always
    image: java-services
    expose:
      - 8080

  ai-services:
    container_name: ai-services
    hostname: ai-services
    restart: always
    image: java-services
    expose:
      - 8080

  action-response-services:
    container_name: action-response-services
    hostname: action-response-services
    restart: always
    image: nodejs-services
    expose:
      - 8001

  client-api:
    container_name: client-api
    hostname: client-api
    restart: always
    image: java-services
    expose:
      - 8080

  world-change-services:
    container_name: world-change-services
    hostname: world-change-services
    restart: always
    image: java-services
    expose:
      - 8080
      