apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: action-response-services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: action-response-services
        tier-name: action-response-services-tier
    spec:
      containers:
        - name: action-response-services
          image: java-services
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: action-response-services
spec:
  selector:
    name: action-response-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
