apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-load
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app-load
    spec:
      containers:
        - name: app-load
          image: app-load
          imagePullPolicy: Never
      restartPolicy: Always