apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chat-services
        tier-name: chat-services-tier
    spec:
      containers:
        - name: chat-services
          image: nodejs-services
          imagePullPolicy: Never
          ports:
          - containerPort: 8001
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: chat-services
spec:
  selector:
    name: chat-services
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
status:
  loadBalancer: {}
