apiVersion: v1
data:
  ACCOUNT_ACCESS_KEY: 958962a3-b8bc-4bb3-8af7-f233674bda81
  ACCOUNT_NAME: customer1
  APPLICATION_NAME: AD-Nite
  CONTROLLER_HOST: ec2-34-221-170-201.us-west-2.compute.amazonaws.com
  CONTROLLER_PORT: "8090"
  CONTROLLER_SSL_ENABLED: "false"
  MA_NAME: AD-Nite
kind: ConfigMap
metadata:
  name: controller-config