apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: sim-os-agent
spec: 
  template: 
    metadata: 
      labels: 
        name: sim-os-agent
    spec:
      serviceAccountName: appd-sim-agent
      containers:
      - env:
        - name: ACCOUNT_ACCESS_KEY
          value: 8083d850-0dbb-42b6-8d58-4047a54e5ffc
        - name: ACCOUNT_NAME
          value: customer1
        - name: APPLICATION_NAME
          value: OS-App1
        - name: CONTROLLER_HOST
          value: 454controllernossh-damademo-bio0c4pc.srv.ravcloud.com
        - name: CONTROLLER_PORT
          value: "8090"
        - name: CONTROLLER_SSL_ENABLED
          value: "false"
        - name: EVENT_ENDPOINT
          value: 454controllernossh-damademo-bio0c4pc.srv.ravcloud.com:9080
        - name: FULL_ACCOUNT_NAME
          value: customer1_58eada16-c7f2-40ba-a2ce-61bcadf11a0f
        - name: IS_K8_DEPLOYMENT
          value: "true"
        - name: TIER_NAME_FROM
          value: CONTAINER_LABEL
        - name: TIER_NAME_FROM_VALUE
          value: tier-name
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METRIC_LIMIT
          value: "2000"
        image: jdbarfield/dynamic-attach-ma:k8-1.1
        securityContext:
          privileged: true
        name: sim-os-agent
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: shared-files
        path: /sharedFiles
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: machine-agent
spec:
  selector:
    name: sim-os-agent
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}